// <auto-generated />
using AuthServer.ConfigStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthServer.Migrations
{
    [DbContext(typeof(ConfigurationStoreContext))]
    [Migration("20200905123646_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthServer.ConfigStore.ApiResourceEntity", b =>
                {
                    b.Property<string>("ApiResourceName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiResourceData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApiResourceName");

                    b.ToTable("ApiResources");
                });

            modelBuilder.Entity("AuthServer.ConfigStore.ClientEntity", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AuthServer.ConfigStore.IdentityResourceEntity", b =>
                {
                    b.Property<string>("IdentityResourceName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityResourceData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentityResourceName");

                    b.ToTable("IdentityResources");
                });

            modelBuilder.Entity("AuthServer.ConfigStore.ScopeEntity", b =>
                {
                    b.Property<string>("ApiScopeName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiScopeData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApiScopeName");

                    b.ToTable("Scopes");
                });
#pragma warning restore 612, 618
        }
    }
}
